// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53nvguVKSLKTHu4pT-acYPtg0dS-E-Bg',
    appId: '1:264963123926:web:e4787973b5d2619a203777',
    messagingSenderId: '264963123926',
    projectId: 'ai-astrology-fcbf8',
    authDomain: 'ai-astrology-fcbf8.firebaseapp.com',
    storageBucket: 'ai-astrology-fcbf8.firebasestorage.app',
    measurementId: 'G-BM84S3BEWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlPaTmBZTYImXHxbbCHJs7h-eeV54iTk',
    appId: '1:264963123926:android:400b0f27fa42921b203777',
    messagingSenderId: '264963123926',
    projectId: 'ai-astrology-fcbf8',
    storageBucket: 'ai-astrology-fcbf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcS0QZ-P_HSfDp-wFG2gNFUcO8kdWGdA',
    appId: '1:264963123926:ios:38fbd28d5fac8a78203777',
    messagingSenderId: '264963123926',
    projectId: 'ai-astrology-fcbf8',
    storageBucket: 'ai-astrology-fcbf8.firebasestorage.app',
    iosBundleId: 'com.example.aiAstrology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcS0QZ-P_HSfDp-wFG2gNFUcO8kdWGdA',
    appId: '1:264963123926:ios:38fbd28d5fac8a78203777',
    messagingSenderId: '264963123926',
    projectId: 'ai-astrology-fcbf8',
    storageBucket: 'ai-astrology-fcbf8.firebasestorage.app',
    iosBundleId: 'com.example.aiAstrology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB53nvguVKSLKTHu4pT-acYPtg0dS-E-Bg',
    appId: '1:264963123926:web:493f6b11ee72f418203777',
    messagingSenderId: '264963123926',
    projectId: 'ai-astrology-fcbf8',
    authDomain: 'ai-astrology-fcbf8.firebaseapp.com',
    storageBucket: 'ai-astrology-fcbf8.firebasestorage.app',
    measurementId: 'G-7J77YZKV6T',
  );

}